apiVersion: v1
kind: Service
metadata:
  name: clock-wise
  namespace: microservices
spec:
  selector:
    app: clock-wise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
  type: LoadBalancer
